// Generated by CoffeeScript 1.3.3
(function() {

  buster.testCase("ConnectivityMap with maps loaded", {
    setUp: function() {
      return this.url = 'dummy.js';
    },
    "URL is registered on XHR": function() {
      var request;
      request = new XMLHttpRequest();
      request.open('GET', this.url, false);
      request.send();
      assert.urlLoaded("dummy.js");
      return expect("dummy.js").toBeAnLoadedUrl();
    },
    "URL is registered when adding a script element to head": function() {
      var script;
      script = document.createElement("script");
      script.type = "text/javascript";
      script.src = this.url;
      document.head.appendChild(script);
      assert.urlLoaded("dummy.js");
      return expect("dummy.js").toBeAnLoadedUrl();
    },
    "URL is registered when adding a script element to body": function() {
      var script;
      script = document.createElement("script");
      script.type = "text/javascript";
      script.src = this.url;
      document.body.appendChild(script);
      assert.urlLoaded("dummy.js");
      return expect("dummy.js").toBeAnLoadedUrl();
    }
  });

}).call(this);
