// Generated by CoffeeScript 1.3.3
(function() {
  var config;

  config = module.exports;

  config["My tests"] = {
    rootPath: "../",
    environment: "browser",
    testHelpers: ['lib/*.js'],
    resources: [],
    sources: [],
    tests: ["test/*-test.js"]
  };

}).call(this);
