// Generated by CoffeeScript 1.3.3
(function() {

  window.String.prototype.endsWith = function(suffix) {
    return this.indexOf(suffix, this.length - suffix.length) !== -1;
  };

  buster.assertions.add("urlRequest", {
    assert: function(server, url) {
      var foundUrl, request, script, scripts, _i, _j, _len, _len1, _ref;
      scripts = document.getElementsByTagName('script');
      _ref = server.requests;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        request = _ref[_i];
        foundUrl = request.url;
        if (foundUrl.endsWith(url)) {
          return true;
        }
      }
      for (_j = 0, _len1 = scripts.length; _j < _len1; _j++) {
        script = scripts[_j];
        foundUrl = script.src;
        if (foundUrl.endsWith(url)) {
          return true;
        }
      }
      return false;
    },
    values: function(server, url, message) {
      if (!(message != null)) {
        message = '';
      }
      return [server, url, message ? message + ": " : message];
    },
    assertMessage: "${2}Expected ${1} to have been loaded",
    refuteMessage: "${2}Expected ${1} to not have been loaded",
    expectation: 'toHaveRequestedTheUrl'
  });

}).call(this);
