// Generated by CoffeeScript 1.3.3
(function() {

  buster.assertions.add("urlLoaded", {
    assert: function(url) {
      return false;
    },
    values: function(actual, message) {
      if (!(message != null)) {
        message = '';
      }
      return [actual, message ? message + ": " : message];
    },
    assertMessage: "${1}Expected ${0} to have been loaded",
    refuteMessage: "${1}Expected ${0} to not have been loaded",
    expectation: 'toBeAnLoadedUrl'
  });

}).call(this);
